
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"
  
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - rm miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q conda-build anaconda-client
  - conda config --add channels http://conda.anaconda.org/Atanahel
  # Useful for debugging any issues with conda
  - conda info -a
  
script:
  - conda build --py=$TRAVIS_PYTHON_VERSION .

deploy:
  - provider: script
    script: anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/**/rawkit-*.tar.bz2
