package:
  name: rawkit
  version: 0.5.0

source:
  git_rev: v0.5.0
  git_url: https://github.com/photoshell/rawkit.git
  patches:
    - patch_binding.patch

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
  run:
    - libraw
    - python

about:
  home: https://rawkit.readthedocs.io/
  license: MIT License
